"""ai providers, assistant, live notifications (NOTIFY trigger), web push, invites, tasks, onboarding

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 12:14:03.280102

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


NEW_TENANT_TABLES = ("invites", "push_subscriptions", "assistant_conversations", "assistant_messages")

# Instant notifications (ADR-012): every committed notification row is announced on channel `forsa_live`.
# NOTIFY is transactional — listeners only hear about rows that were actually committed. The payload is kept
# small (< 8000 bytes): listeners re-read details through the RLS-protected API.
NOTIFY_FUNCTION = """
CREATE OR REPLACE FUNCTION forsa_notify_live() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_notify('forsa_live', json_build_object(
    'kind', 'notification', 'org_id', NEW.org_id, 'user_id', NEW.user_id, 'id', NEW.id,
    'category', NEW.category, 'priority', NEW.priority, 'title', left(NEW.title, 200)
  )::text);
  RETURN NEW;
END $$;
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_provider_settings",
        sa.Column("provider_id", sa.String(length=40), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("fast_model", sa.String(length=120), nullable=True),
        sa.Column("reasoning_model", sa.String(length=120), nullable=True),
        sa.Column("decision_model", sa.String(length=120), nullable=True),
        sa.Column("max_sensitivity", sa.String(length=20), nullable=True),
        sa.Column("dpa_reviewed", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], name=op.f("fk_ai_provider_settings_updated_by_users")),
        sa.PrimaryKeyConstraint("provider_id", name=op.f("pk_ai_provider_settings")),
    )
    op.create_table(
        "assistant_conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_assistant_conversations_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_assistant_conversations_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_conversations")),
    )
    op.create_index(op.f("ix_assistant_conversations_org_id"), "assistant_conversations", ["org_id"], unique=False)
    op.create_index(op.f("ix_assistant_conversations_user_id"), "assistant_conversations", ["user_id"], unique=False)
    op.create_table(
        "invites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], name=op.f("fk_invites_invited_by_users")),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_invites_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invites")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invites_token_hash")),
    )
    op.create_index(op.f("ix_invites_org_id"), "invites", ["org_id"], unique=False)
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("endpoint", sa.String(length=1000), nullable=False),
        sa.Column("p256dh", sa.String(length=200), nullable=False),
        sa.Column("auth", sa.String(length=100), nullable=False),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_push_subscriptions_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_push_subscriptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_subscriptions")),
        sa.UniqueConstraint("endpoint", name=op.f("uq_push_subscriptions_endpoint")),
    )
    op.create_index(op.f("ix_push_subscriptions_org_id"), "push_subscriptions", ["org_id"], unique=False)
    op.create_index(op.f("ix_push_subscriptions_user_id"), "push_subscriptions", ["user_id"], unique=False)
    op.create_table(
        "assistant_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["assistant_conversations.id"],
            name=op.f("fk_assistant_messages_conversation_id_assistant_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_assistant_messages_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_messages")),
    )
    op.create_index(
        op.f("ix_assistant_messages_conversation_id"), "assistant_messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_assistant_messages_org_id"), "assistant_messages", ["org_id"], unique=False)
    op.add_column("companies", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("companies", sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "memberships",
        sa.Column("notification_prefs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
    )
    op.add_column("notifications", sa.Column("priority", sa.String(length=10), server_default="normal", nullable=False))
    op.add_column("notifications", sa.Column("pushed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tasks", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("tasks", sa.Column("source", sa.String(length=20), server_default="manual", nullable=False))
    op.add_column("tasks", sa.Column("source_key", sa.String(length=200), nullable=True))
    op.add_column("tasks", sa.Column("created_by", sa.UUID(), nullable=True))
    op.create_unique_constraint(op.f("uq_tasks_source_key"), "tasks", ["source_key"])
    op.create_foreign_key(op.f("fk_tasks_created_by_users"), "tasks", "users", ["created_by"], ["id"])
    # ### end Alembic commands ###
    for table in NEW_TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (forsa_rls_system() OR org_id = forsa_rls_org()) "
            "WITH CHECK (forsa_rls_system() OR org_id = forsa_rls_org())"
        )
    op.execute(NOTIFY_FUNCTION)
    op.execute(
        "CREATE TRIGGER notifications_live AFTER INSERT ON notifications "
        "FOR EACH ROW EXECUTE FUNCTION forsa_notify_live()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS notifications_live ON notifications")
    op.execute("DROP FUNCTION IF EXISTS forsa_notify_live()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_tasks_created_by_users"), "tasks", type_="foreignkey")
    op.drop_constraint(op.f("uq_tasks_source_key"), "tasks", type_="unique")
    op.drop_column("tasks", "created_by")
    op.drop_column("tasks", "source_key")
    op.drop_column("tasks", "source")
    op.drop_column("tasks", "description")
    op.drop_column("notifications", "pushed_at")
    op.drop_column("notifications", "priority")
    op.drop_column("memberships", "notification_prefs")
    op.drop_column("companies", "onboarding_completed_at")
    op.drop_column("companies", "description")
    op.drop_index(op.f("ix_assistant_messages_org_id"), table_name="assistant_messages")
    op.drop_index(op.f("ix_assistant_messages_conversation_id"), table_name="assistant_messages")
    op.drop_table("assistant_messages")
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_index(op.f("ix_push_subscriptions_org_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.drop_index(op.f("ix_invites_org_id"), table_name="invites")
    op.drop_table("invites")
    op.drop_index(op.f("ix_assistant_conversations_user_id"), table_name="assistant_conversations")
    op.drop_index(op.f("ix_assistant_conversations_org_id"), table_name="assistant_conversations")
    op.drop_table("assistant_conversations")
    op.drop_table("ai_provider_settings")
    # ### end Alembic commands ###
