"""real sources: attributes, debarments

Revision ID: 0003_real_sources
Revises: 0002
Create Date: 2026-09-24 13:21:10.768395

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003_real_sources"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "debarments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_key", sa.String(length=80), nullable=False),
        sa.Column("external_ref", sa.String(length=200), nullable=False),
        sa.Column("entity_name", sa.String(length=300), nullable=False),
        sa.Column("name_key", sa.String(length=300), nullable=False),
        sa.Column("registry_number", sa.String(length=80), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("nature", sa.Text(), nullable=True),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.Column("effective_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_url", sa.String(length=1000), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_debarments")),
        sa.UniqueConstraint("source_key", "external_ref", name=op.f("uq_debarments_source_key_external_ref")),
    )
    op.create_index(op.f("ix_debarments_name_key"), "debarments", ["name_key"], unique=False)
    op.add_column(
        "opportunities",
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
    )
    op.create_index("ix_opportunities_kind_published", "opportunities", ["kind", "published_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_opportunities_kind_published", table_name="opportunities")
    op.drop_column("opportunities", "attributes")
    op.drop_index(op.f("ix_debarments_name_key"), table_name="debarments")
    op.drop_table("debarments")
    # ### end Alembic commands ###
